apiVersion: v1
kind: Service
metadata:
  name: fontem-linguistics
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: fontem-linguistics
  ports:
    - name: http
      port: 8080
      targetPort: 8080
  type: ClusterIP
